require('dotenv').config()
const express = require('express')
const router = express.Router()
const User = require('../models/user')
const jwt = require('jsonwebtoken')

router.get('/', (req, res)=>{
    res.send('log in page')
})
router.get('/seed', async (req, res)=>{
    await User.deleteMany({})
    // const starterUsers = [
    //     {username:'a', password:'a'},
    //     {username:'b', password:'b'},
    //     {username:'c', password:'c'},
    //     {username:'d', password:'d'},
    //     {username:'e', password:'e'},
    //     {username:'f', password:'f'},
    // ]
    const starterUsers = [
        {
          username: 'user1',
          password: 'user1',
          firstName: 'John',
          lastName: 'Doe',
          age: 25,
          job: 'Software Developer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [0, 2, 4],
          promptAnswers: ['Blue', 'Pizza', 'Bohemian Rhapsody'],
          profilePic: 'https://picsum.photos/200/200',
          pictures: ['https://picsum.photos/200/300', 'https://picsum.photos/300/300', 'https://picsum.photos/300/200'],
        },
        {
          username: 'user2',
          password: 'user2',
          firstName: 'Jane',
          lastName: 'Smith',
          age: 30,
          job: 'Data Scientist',
          gender: 1,
          interestedIn: [0],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Dog', 'Pasta', 'The Shawshank Redemption'],
          profilePic: 'https://picsum.photos/200/201',
          pictures: ['https://picsum.photos/200/301', 'https://picsum.photos/300/301', 'https://picsum.photos/300/201'],
        },
        {
          username: 'user3',
          password: 'user3',
          firstName: 'Chris',
          lastName: 'Johnson',
          age: 28,
          job: 'UX Designer',
          gender: 0,
          interestedIn: [0, 1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Bohemian Rhapsody', 'Green'],
          profilePic: 'https://picsum.photos/200/202',
          pictures: ['https://picsum.photos/200/302', 'https://picsum.photos/300/302', 'https://picsum.photos/300/202'],
        },
        {
          username: 'user4',
          password: 'user4',
          firstName: 'Alex',
          lastName: 'Taylor',
          age: 35,
          job: 'Marketing Manager',
          gender: 2,
          interestedIn: [0, 1, 2],
          promptChoices: [3, 1, 5],
          promptAnswers: ['The Dark Knight', 'Pasta', '1984'],
          profilePic: 'https://picsum.photos/200/203',
          pictures: ['https://picsum.photos/200/303', 'https://picsum.photos/300/303', 'https://picsum.photos/300/203'],
        },
        {
          username: 'user5',
          password: 'user5',
          firstName: 'Sam',
          lastName: 'Miller',
          age: 22,
          job: 'Student',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Bohemian Rhapsody', 'Sushi', 'Blue'],
          profilePic: 'https://picsum.photos/200/204',
          pictures: ['https://picsum.photos/200/304', 'https://picsum.photos/300/304', 'https://picsum.photos/300/204'],
        },
        {
          username: 'user6',
          password: 'user6',
          firstName: 'Emily',
          lastName: 'Williams',
          age: 27,
          job: 'Graphic Designer',
          gender: 1,
          interestedIn: [0],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Cat', 'Burgers', 'Inception'],
          profilePic: 'https://picsum.photos/200/205',
          pictures: ['https://picsum.photos/200/305', 'https://picsum.photos/300/305', 'https://picsum.photos/300/205'],
        },
        {
          username: 'user7',
          password: 'user7',
          firstName: 'Michael',
          lastName: 'Clark',
          age: 32,
          job: 'Engineer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Hotel California', 'Green'],
          profilePic: 'https://picsum.photos/200/206',
          pictures: ['https://picsum.photos/200/306', 'https://picsum.photos/300/306', 'https://picsum.photos/300/206'],
        },
        {
          username: 'user8',
          password: 'user8',
          firstName: 'Emma',
          lastName: 'Johnson',
          age: 29,
          job: 'Teacher',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [3, 1, 5],
          promptAnswers: ['The Shawshank Redemption', 'Pasta', 'Purple'],
          profilePic: 'https://picsum.photos/200/207',
          pictures: ['https://picsum.photos/200/307', 'https://picsum.photos/300/307', 'https://picsum.photos/300/207'],
        },
        {
          username: 'user9',
          password: 'user9',
          firstName: 'Ryan',
          lastName: 'Baker',
          age: 26,
          job: 'Fitness Trainer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Imagine', 'Salad', 'Blue'],
          profilePic: 'https://picsum.photos/200/208',
          pictures: ['https://picsum.photos/200/308', 'https://picsum.photos/300/308', 'https://picsum.photos/300/208'],
        },
        {
          username: 'user10',
          password: 'user10',
          firstName: 'Olivia',
          lastName: 'Smith',
          age: 31,
          job: 'Marketing Specialist',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [3, 1, 5],
          promptAnswers: ['Inception', 'Pizza', 'Yellow'],
          profilePic: 'https://picsum.photos/200/209',
          pictures: ['https://picsum.photos/200/309', 'https://picsum.photos/300/309', 'https://picsum.photos/300/209'],
        },
        {
          username: 'user11',
          password: 'user11',
          firstName: 'Daniel',
          lastName: 'Brown',
          age: 28,
          job: 'Writer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Stairway to Heaven', 'Green'],
          profilePic: 'https://picsum.photos/201/200',
          pictures: ['https://picsum.photos/201/300', 'https://picsum.photos/301/300', 'https://picsum.photos/301/200'],
        },
        {
          username: 'user12',
          password: 'user12',
          firstName: 'Sophia',
          lastName: 'Davis',
          age: 34,
          job: 'Architect',
          gender: 1,
          interestedIn: [0],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Dog', 'Burgers', 'The Dark Knight'],
          profilePic: 'https://picsum.photos/202/200',
          pictures: ['https://picsum.photos/202/300', 'https://picsum.photos/302/300', 'https://picsum.photos/302/200'],
        },
        {
          username: 'user13',
          password: 'user13',
          firstName: 'Ethan',
          lastName: 'Moore',
          age: 27,
          job: 'Software Engineer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Bohemian Rhapsody', 'Sushi', 'Blue'],
          profilePic: 'https://picsum.photos/203/200',
          pictures: ['https://picsum.photos/203/300', 'https://picsum.photos/303/300', 'https://picsum.photos/303/200'],
        },
        {
          username: 'user14',
          password: 'user14',
          firstName: 'Isabella',
          lastName: 'White',
          age: 29,
          job: 'Data Analyst',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [3, 1, 5],
          promptAnswers: ['The Shawshank Redemption', 'Pizza', 'Yellow'],
          profilePic: 'https://picsum.photos/204/200',
          pictures: ['https://picsum.photos/204/300', 'https://picsum.photos/304/300', 'https://picsum.photos/304/200'],
        },
        {
          username: 'user15',
          password: 'user15',
          firstName: 'Matthew',
          lastName: 'Jones',
          age: 25,
          job: 'Graphic Designer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Hotel California', 'Green'],
          profilePic: 'https://picsum.photos/205/200',
          pictures: ['https://picsum.photos/205/300', 'https://picsum.photos/305/300', 'https://picsum.photos/305/200'],
        },
        {
          username: 'user16',
          password: 'user16',
          firstName: 'Ava',
          lastName: 'Miller',
          age: 31,
          job: 'Teacher',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Cat', 'Burgers', 'The Dark Knight'],
          profilePic: 'https://picsum.photos/206/200',
          pictures: ['https://picsum.photos/206/300', 'https://picsum.photos/306/300', 'https://picsum.photos/306/200'],
        },
        {
          username: 'user17',
          password: 'user17',
          firstName: 'David',
          lastName: 'Anderson',
          age: 28,
          job: 'UX Designer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Imagine', 'Salad', 'Blue'],
          profilePic: 'https://picsum.photos/207/200',
          pictures: ['https://picsum.photos/207/300', 'https://picsum.photos/307/300', 'https://picsum.photos/307/200'],
        },
        {
          username: 'user18',
          password: 'user18',
          firstName: 'Mia',
          lastName: 'Garcia',
          age: 34,
          job: 'Marketing Manager',
          gender: 1,
          interestedIn: [0],
          promptChoices: [3, 1, 5],
          promptAnswers: ['Inception', 'Pasta', 'Purple'],
          profilePic: 'https://picsum.photos/208/200',
          pictures: ['https://picsum.photos/208/300', 'https://picsum.photos/308/300', 'https://picsum.photos/308/200'],
        },
        {
          username: 'user19',
          password: 'user19',
          firstName: 'Christopher',
          lastName: 'Walker',
          age: 26,
          job: 'Fitness Trainer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Stairway to Heaven', 'Green'],
          profilePic: 'https://picsum.photos/209/200',
          pictures: ['https://picsum.photos/209/300', 'https://picsum.photos/309/300', 'https://picsum.photos/309/200'],
        },
        {
          username: 'user20',
          password: 'user20',
          firstName: 'Sophie',
          lastName: 'Hill',
          age: 31,
          job: 'Marketing Specialist',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Dog', 'Burgers', 'The Dark Knight'],
          profilePic: 'https://picsum.photos/200/210',
          pictures: ['https://picsum.photos/200/310', 'https://picsum.photos/310/300', 'https://picsum.photos/310/200'],
        },
        {
          username: 'user21',
          password: 'user21',
          firstName: 'Nicholas',
          lastName: 'Adams',
          age: 28,
          job: 'Writer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Bohemian Rhapsody', 'Sushi', 'Blue'],
          profilePic: 'https://picsum.photos/200/220',
          pictures: ['https://picsum.photos/200/320', 'https://picsum.photos/300/320', 'https://picsum.photos/300/220'],
        },
        {
          username: 'user22',
          password: 'user22',
          firstName: 'Grace',
          lastName: 'Baker',
          age: 34,
          job: 'Architect',
          gender: 1,
          interestedIn: [0],
          promptChoices: [3, 1, 5],
          promptAnswers: ['The Shawshank Redemption', 'Pizza', 'Yellow'],
          profilePic: 'https://picsum.photos/200/230',
          pictures: ['https://picsum.photos/200/330', 'https://picsum.photos/300/330', 'https://picsum.photos/300/230'],
        },
        {
          username: 'user23',
          password: 'user23',
          firstName: 'Andrew',
          lastName: 'Barnes',
          age: 27,
          job: 'Software Engineer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 0],
          promptAnswers: ['Bohemian Rhapsody', 'Sushi', 'Blue'],
          profilePic: 'https://picsum.photos/200/240',
          pictures: ['https://picsum.photos/200/340', 'https://picsum.photos/300/340', 'https://picsum.photos/300/240'],
        },
        {
          username: 'user24',
          password: 'user24',
          firstName: 'Ella',
          lastName: 'Young',
          age: 29,
          job: 'Data Analyst',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [3, 1, 5],
          promptAnswers: ['The Shawshank Redemption', 'Pizza', 'Yellow'],
          profilePic: 'https://picsum.photos/200/250',
          pictures: ['https://picsum.photos/200/350', 'https://picsum.photos/300/350', 'https://picsum.photos/300/250'],
        },
        {
          username: 'user25',
          password: 'user25',
          firstName: 'Jacob',
          lastName: 'Clark',
          age: 25,
          job: 'Graphic Designer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [2, 4, 0],
          promptAnswers: ['Sushi', 'Hotel California', 'Green'],
          profilePic: 'https://picsum.photos/200/260',
          pictures: ['https://picsum.photos/200/360', 'https://picsum.photos/300/360', 'https://picsum.photos/300/260'],
        },
        {
          username: 'user26',
          password: 'user26',
          firstName: 'Avery',
          lastName: 'King',
          age: 31,
          job: 'Teacher',
          gender: 1,
          interestedIn: [0, 2],
          promptChoices: [1, 3, 5],
          promptAnswers: ['Cat', 'Burgers', 'The Dark Knight'],
          profilePic: 'https://picsum.photos/210/200',
          pictures: ['https://picsum.photos/210/300', 'https://picsum.photos/310/300', 'https://picsum.photos/310/200'],
        },
        {
          username: 'user27',
          password: 'user27',
          firstName: 'Benjamin',
          lastName: 'Harris',
          age: 28,
          job: 'UX Designer',
          gender: 0,
          interestedIn: [1],
          promptChoices: [4, 2, 5],
            promptAnswers: ['Imagine', 'Salad', 'Blue'],
            profilePic: 'https://picsum.photos/200/200',
            pictures: ['https://picsum.photos/200/300', 'https://picsum.photos/300/300', 'https://picsum.photos/300/200'],
        },
    ]
    await User.create(starterUsers)
    const users = await User.find({})
    res.json(users)
})

router.post('/login', async (req, res)=>{
    const userToLogin = await User.findOne({username: req.body.username})
    let passwordMatches = false
    if (userToLogin){
        passwordMatches = userToLogin.password === req.body.password
    }
    if (userToLogin&&passwordMatches){
        req.session.userid = userToLogin._id
        res.json(req.session)
        // const token = jwt.sign({userid: userToLogin._id}, process.env.SECRET)
        // req.session.token = token
        // res.json({token})
    } else {
        res.status(400).json('incorrect username or password')
    }
})

router.post('/signup', async (req, res)=>{
    const createdUser = await User.create(req.body)
    res.json(createdUser)
})

router.get('/logout', (req, res)=>{
    console.log(req.session.token.userid);
    req.session.destroy()
    console.log('logged out');
    console.log(req.session.userid);
    res.redirect('/')
})

module.exports = router